### PR TITLE
Capture environment.

### PR DESCRIPTION
**Pull request by ian-r-rose**
@Swanson-Hysell can you check at some point if this environment works for you? Then we will know we are operating in as close to the same environment as possible.

### CODE REVIEW

**Comment by Swanson-Hysell** [comment]
When I try to install the environment using conda, I bump into some issues:

```
$ conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............

ResolvePackageNotFound: 
  - gst-plugins-base 1.8.0 0
```

I progressively removed that package and others from the .yml and found a number of other packages that conda couldn't resolve:
```
ResolvePackageNotFound: 
  - gstreamer 1.8.0 1

ResolvePackageNotFound: 
  - qt 5.6.2 7

ResolvePackageNotFound: 
  - intel-openmp 2018.0.0 hc7b2577_8

ResolvePackageNotFound: 
  - libgcc 7.2.0 h69d50b8_2

ResolvePackageNotFound: 
  - libgcc-ng 7.2.0 h7cc24e2_2

ResolvePackageNotFound: 
  - libgfortran-ng 7.2.0 h9f7466a_2

ResolvePackageNotFound: 
  - libstdcxx-ng 7.2.0 h7a57d05_2

ResolvePackageNotFound: 
  - mkl 2018.0.1 h19d6760_4

ResolvePackageNotFound: 
  - numpy 1.14.0 py36h3dfced4_0

ResolvePackageNotFound: 
  - scipy 1.0.0 py36hbf646e7_0
```

**Comment by ian-r-rose** [comment]
Hmm, that's unfortunate. Maybe it is too much to ask for the same environment to work on both Mac OS and Linux.

I wonder if we can get a minimal set working that includes just the top-level packages (cartopy, pymc, scipy, etc), and just let conda take care of the rest.

**Comment by Swanson-Hysell** [comment]
Here is my environment.yml that seems to work (I tested it on ```invert_two_euler_poles.py```). It is now in the repo as ```environment_nsh.yml``` via 5a0b2ef. You want to see if this environment works for you?

```
name: bayesian_plate
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.22.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- blas=1.1=openblas
- ca-certificates=2017.11.5=0
- cartopy=0.15.1=py36_5
- certifi=2017.11.5=py36_0
- cffi=1.11.2=py36_0
- chardet=3.0.4=py36_0
- cryptography=2.1.4=py36_0
- cycler=0.10.0=py36_0
- freetype=2.8.1=0
- geos=3.6.2=1
- icu=58.2=0
- idna=2.6=py36_1
- jpeg=9b=2
- libffi=3.2.1=3
- libgfortran=3.0.0=0
- libiconv=1.15=0
- libpng=1.6.34=0
- libtiff=4.0.9=0
- libxml2=2.9.7=0
- libxslt=1.1.32=0
- lxml=4.1.1=py36_0
- matplotlib=2.1.1=py36_2
- ncurses=5.9=10
- numpy=1.13.3=py36_blas_openblas_200
- olefile=0.44=py36_0
- openblas=0.2.19=2
- openssl=1.0.2n=0
- owslib=0.16.0=py_0
- pillow=5.0.0=py36_0
- pip=9.0.1=py36_1
- proj4=4.9.3=5
- pycparser=2.18=py36_0
- pyepsg=0.3.2=py36_0
- pymc=2.3.6=py36_1
- pyopenssl=17.4.0=py36_0
- pyparsing=2.2.0=py36_0
- pyproj=1.9.5.1=py36_0
- pyshp=1.2.12=py_0
- pysocks=1.6.8=py36_1
- python=3.6.4=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_2
- readline=7.0=0
- requests=2.18.4=py36_1
- scipy=0.19.1=py36_blas_openblas_202
- setuptools=38.4.0=py36_0
- shapely=1.6.3=py36_0
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- tornado=4.5.3=py36_0
- urllib3=1.22=py36_0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - backports.functools-lru-cache==1.4
prefix: /anaconda3/envs/bayesian_plate
```

**Comment by Swanson-Hysell** [comment]
As I note in the commit, this environment was achieved with the following commands:
```
> conda create --name bayesian_plate python=3.6
> conda install numpy
> conda install pymc
> conda install cartopy
```
There was then an openblas related error which was resolved via:
```
> conda install openblas=0.2.19
```
This openblas install downgraded numpy and scipy.

**Comment by ian-r-rose** [comment]
Getting closer... I had to change the line containing libgfortran to 
```yml
- libgfortran=3.0.0=1
```
in order for it to install.

**Comment by Swanson-Hysell** [comment]
If I change my libgfortran to that version, I get numpy breakage related to the openblas issue:

```
Traceback (most recent call last):
  File "/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/bayesian_plate/lib/libopenblasp-r0.2.19.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "invert_two_euler_poles.py", line 4, in <module>
    import numpy as np
  File "/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen(/anaconda3/envs/bayesian_plate/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/bayesian_plate/lib/libopenblasp-r0.2.19.dylib
  Reason: image not found
```

**Comment by ian-r-rose** [comment]
Ugh, reproducibility is hard. I am also in the process of running down a small bug in pymc right now, which will probably require us to bump the version of that.

**Comment by Swanson-Hysell** [comment]
Importing pymc was where I ran into the openblas issue so perhaps that could be resolved with a different pymc version as well.

**Comment by ian-r-rose** [comment]
For now I think it's probably okay for us to have separate, (mostly) equivalent environments, but before putting this in amber, we should probably make sure we have a satisfactory story for reproducibility.

**Comment by Swanson-Hysell** [comment]
That sounds good. They are pretty darn close to another right now.

**Pull request merged**
