### PR TITLE
add additional one euler synthetic; plot the hidden euler position and rate for the existing ones

### PR DESCRIPTION
**Pull request by Swanson-Hysell**
Another example one euler synthetic is generated that results in a less symmetric Euler position posterior.

Small updates to the plotting now plot the Euler pole position and rate in the existing synthetics which I think will be helpful for the reader.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Do you have an image showing the change?

Also, can you add the new figure to the Makefile?

**Comment by Swanson-Hysell** [comment]
Here is what it looks like with the stars:
screen shot 2018-01-18 at 5 53 32 pm

Here is what one Euler scenario b looks like:

screen shot 2018-01-18 at 5 53 39 pm

**Comment by Swanson-Hysell** [comment]
Just added one Euler scenario b to the Makefile

**Review by ian-r-rose — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
